API_KEY = 'PUT YOUR OPENAI API KEY HERE'
WEBHOOK_URL = 'PUT YOUR DISCORD WEBHOOK LINK HERE'
MINIMUM = 70 #The minimum score needed to send the offer to you
RESUME = """
PASTE THE TEXT CONTENT OF YOUR RESUME HERE
"""
